### ISSUE TITLE
Deploy does not process redirects from netlify.toml

### ISSUE THREAD

**Issue by iiroj** [netlify/cli#111]
**- Do you want to request a *feature* or report a *bug*?**

~This is a feature request to support processing redirects, either from `netlify.toml` or `_redirects`.~

This is a feature request to support processing redirects from `netlify.toml`.

**- What is the current behavior?**

~It seems the `_headers` file is consumed, but redirects are not. I've tried both having a `netlify.toml` file in the current directory where `netlify` is run, and a `_redirects` file in the uploaded build folder.~

It seems the `_headers` and `_redirects` files are consumed, but `netlify.toml` is not.

**- If the current behavior is a bug, please provide the steps to reproduce.**

**- What is the expected behavior?**

Redirects should be processed from a `netlify.toml` file in the current `$PWD`, when deploying using `netlify`.

**- Please mention your node.js, and operating system version.**

I'm running this in GitLab CI with the `node:alpine` Docker image, so it's the latest node version 10.10.1 on Alpine 3.8.

**Comment by iiroj** [comment]
It seems I had invalid syntax in my `_redirects` file. After fixing it, redirects are working! Still, they do not work from `netlify.toml`. Feel free to close this issue if it's out of scope.

**Comment by DirtyF** [comment]
Any reason why redirections should work from the config file? 
Having redirects in a dedicated file allows generators like Hugo to output redirections through a template.

**Comment by bcomnes** [comment]
@DirtyF our platform supports cdn node redirects.  While some SSGs support redirects, we also aim to support it at the platform levels, so we need to make the cli support it as well.

**Comment by iiroj** [comment]
@bcomnes

This state had the `netlify.toml` file. It’s a basic gatsby project: https://github.com/iiroj/iiro.fi/tree/673190ef20ee91885a6710e52f1bcc60b971868d

For what it’s worth, I’m pretty sure it didn’t work with `netlifyctl` either. I ran both from GitLab CI (see `.gitlab-ci.yml`). Gitlab CI will clone the repo to a directory and then run any commands in that same directory.

Before switching to manual deploys, the same file worked fine for the default git-webhook style deploy.

**Comment by bcomnes** [comment]
If you are running `netlify-cli@next` it attempts to copy over a netlify.toml into the deploy files automatically.  You can also manually copy these config files into the deploy folder before deploying, and the CDN should pick them up.  We may also have a regression of some sorts that I need to look into.

**Comment by DirtyF** [comment]
> our platform supports cdn node redirects. While some SSGs support redirects, we also aim to support it at the platform levels, so we need to make the cli support it as well.

I get that, I was referring to the fact that you can loop through site pages in a Hugo layout to output a `_redirects` file for Netlify.

**Comment by bcomnes** [comment]
Ah I see.  Apologise for the confusion

**Comment by bcomnes** [comment]
I just released an updated beta (netlify-cli/2.0.0-beta.4).  I also got clarification on how the config files are supposed to behave:

- `_redirecets` and `_headers` files need to be inside the deploy folder in order to be used.  Its up to the user to make sure these are put into the deploy folder during whatever build phase that you have set up.
- A `netlify.toml` file in the root of the project directory will be included in the CLI can find it.  You can also copy or create this into the deploy folder and that version will override any discovered `netlify.toml` file that is found. 

I'm going to open a new issue about maybe adding a warning or prompt if we see `_redirecets` and `_headers` in the project, but not in the deploy folder.

Closing this for now.  If you are still having issues please let me know and we can reopen.

**Comment by michealjroberts** [comment]
This for me is still borked to high heavens.

Please see: ```https://stackoverflow.com/questions/59308045/netlify-deployment-issue-netlify-toml-settings-for-spa```

**Comment by tholder** [comment]
Still not working. May 2022 🙃 - moving to _redirects file in root of project seems to sort.
