### ISSUE TITLE
404 redirects dont work as they do in production

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#415]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**

https://community.netlify.com/t/404-redirect-in-netlify-toml-brings-live-tunnel-link-always-to-a-404-page/1272/5

**Comment by raeesbhatti** [comment]
Fixed in https://github.com/netlify/cli/pull/538

**Comment by ZackBoe** [comment]
I'm still experiencing this with `netlify-cli@2.20.2`. Wasn't sure if this warranted opening a new issue.

I've [deployed](https://test-redirect.netlify.com/) a [test case](https://github.com/ZackBoe/netlify-dev-404-redirect) and am seeing an endless redirect using the following `netlify.toml`

```
[[redirects]]
  from = "/test/*"
  to = "/test/?id=:splat"
  status = 302
```

Dev vs Live:
![9726b5ba](https://user-images.githubusercontent.com/904055/68057804-6ab12400-fccd-11e9-870e-4fdfd2d9bba6.png)

**Comment by paulshryock** [comment]
I'm on version `2.20.2` and I also still do not have working local 404 redirects.

`netlify.toml`:

```toml
[build]
  command = "npm start"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/404?search=:splat"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
```
