### ISSUE TITLE
netlify dev --live can't see live URL message in terminal

### ISSUE THREAD

**Issue by kmcaloon** [netlify/cli#596]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
Running `netlify dev --live` successfully creates tunnel but sometimes I can't see the "connected" message notifying me of the public url.

**- If the current behavior is a bug, please provide the steps to reproduce.**
Reinstalled netlify-cli 2.19.0, reinstalled local gatsby site, run `netlify dev --live, always produces same result.

**- What is the expected behavior?**
Once the tunnel is set up, I should be able to clearly see the notification in the terminal.

**- Local Environment Information**
```
──────────────────────┐
 Current Netlify User │
──────────────────────┘
Email:  kevin+dartdrones@kmcaloon.com
Github: kmcaloon
Teams: 
  kevin-dartdrones's team: Collaborator

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 65.0.1
    Safari: 13.0.2

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: condescending-booth-644542
Netlify TOML: /Applications/MAMP/htdocs/dartdrones.com/netlify.toml
Admin URL:    https://app.netlify.com/sites/condescending-booth-644542
Site URL:     https://condescending-booth-644542.netlify.com
Site Id:      e7591fbe-89a4-4f77-a94b-1256d5d125b1
```

Above pretty much says it all. I have been using `netlify dev --live` for a while without any issues, then for some reason the I stopped seeing the "connected" message with the public URL. It flashes for a split second then is hidden but subsequent terminal output.

Here is an example of what I'm seeing:

<img width="594" alt="Screen Shot 2019-10-29 at 12 38 09 PM" src="https://user-images.githubusercontent.com/10777353/67788623-13028680-fa49-11e9-9dd8-5d61c8f8230f.png">

Sometimes I see this:

<img width="593" alt="Screen Shot 2019-10-29 at 12 27 11 PM" src="https://user-images.githubusercontent.com/10777353/67788687-2d3c6480-fa49-11e9-841c-f7490d82ecd7.png">

Disabling the bundle analyzer doesn't help. Not sure where to start here?

**Comment by MartinRosenberg** [comment]
Same issue here. I thought it was being caused by [gatsby-plugin-ts](https://www.gatsbyjs.org/packages/gatsby-plugin-ts/), but now I'm thinking it's being caused by Gatsby itself, trying to keep its own output clean and accidentally erasing netlify-cli's output in the process.

**Comment by kenjwho** [comment]
Exact same issue happening here.  Also using Gatsby, in case that helps

**Comment by DavidWells** [comment]
This should get solved with https://github.com/netlify/cli/pull/612 @raeesbhatti merged in recently.

Looks like we need to cut a release

**Comment by raeesbhatti** [comment]
I just created a release. @kmcaloon Please update and let me know if it doesn't open the correct URL on `netlify dev --live`

**Comment by kmcaloon** [comment]
Still seeing this with v2.21.0.

<img width="776" alt="Screen Shot 2019-11-30 at 4 22 37 PM" src="https://user-images.githubusercontent.com/10777353/69906197-ba970f80-138d-11ea-9103-e655a4c4c393.png">
