### ISSUE TITLE
Bug?: ◈ Error while killing child process: kill ESRCH - Windows 10

### ISSUE THREAD

**Issue by zync09** [netlify/cli#689]
**- Do you want to request a _feature_ or report a _bug_?**
Bug report

**- What is the current behavior?**
I can't run the netlify dev server at all. It was running fine and now ti seems stuck. Any ideas on how to fix it?

**- If the current behavior is a bug, please provide the steps to reproduce.**
netlify dev

◈ Netlify Dev ◈
◈ Starting Netlify Dev with yarn
Waiting for localhost:3000.
◈ Lambda server is listening on 34567
◈ Error while killing child process: kill ESRCH

**- What is the expected behavior?**
Netlify dev server should run but it doesn't. Even after a reboot and closing down everything and reopening.

**- Local Environment Information**
────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: Windows 10 10.0.17763
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0

────────────────────┐
 Netlify Site Info  │
────────────────────┘
Current site: netlify-playground-nuxt
Netlify TOML: E:\Development\netlify-playground-nuxt\netlify.toml
Admin URL:    https://app.netlify.com/sites/netlify-playground-nuxt
Site URL:     https://netlify-playground-nuxt.netlify.com
Site Id:      30b00e42-264f-41f0-bdd1-7b2ec62e154d

**Comment by nolastan** [comment]
This issue is a dupe of https://github.com/netlify/cli/issues/684 which was resolved 8 days prior. Make sure you're running `v2.30.0` or higher. I ran `npm update netlify` and I'm no longer having this issue.

**Comment by zync09** [comment]
Hi @nolastan,

I uninstalled and reinstalled netlify-cli fresh with yarn and then yarn (uninstalling each time and clearing cache). It was the latest version each time. Still having the same issue though.

`E:\Development\netlify-playground-nuxt (master -> origin)
λ netlify dev
◈ Netlify Dev ◈
◈ Starting Netlify Dev with yarn
Waiting for localhost:3000.
◈ Lambda server is listening on 34567
◈ Error while killing child process: kill ESRCH

E:\Development\netlify-playground-nuxt (master -> origin)
λ netlify -v
netlify-cli/2.30.0 win32-x64 node-v12.14.0`

**Comment by nolastan** [comment]
Yep, I may have spoken to soon. I'm seeing the issue intermittently again. It doesn't appear that https://github.com/netlify/cli/issues/684 resolved the issue.

**Comment by zync09** [comment]
Is there anything else I can post that might help narrow down the problem?

**Comment by elijahseedarita** [comment]
I'm also experiencing the problem, both on Windows 10 and WSL Ubuntu

**Comment by hacknug** [comment]
I'm also getting the error on macOS after a successful build running `netlify dev -c "yarn build"`

**Comment by elijahseedarita** [comment]
I found a solution for Nuxt - with NPM, you need to have a dev script in package.json which runs "nuxt dev". I didn't have this script because I start my nuxt projects from scratch. Adding it fixed the issue

    {
        "scripts": {
            "dev": "nuxt dev"
        }
    }

It might be a good idea to have the nuxt detector work independently from user defined scripts.

**Comment by chs242** [comment]
Hey I'm having the same issue on 2 templates that i deployed straight from netlify CMS. the awake-template which uses nuxt and the netlify-cms-template-for-gridsome which uses gridsome. For both these templates I cloned the github repo and tried to open a dev server using the netlify dev command. Both times the same issue mentioned above occurred. I hadn't fiddled with any code and I made sure I was in the root folder
Any ideas?

**Comment by RaeesBhatti** [comment]
@zync09 Can you please update to the latest version and report back if this is still an issue!

**Comment by Nisfan** [comment]
I am still facing same issue with latest version (2.40.0)

**Comment by SammyIsra** [comment]
Has there been any progress on this issue? I am still facing it on version 2.43.0.

```
>netlify -dev
netlify-cli/2.43.0 win32-x64 node-v13.12.0
```

This happens regardless of whether the console is in Admin mode or not

**Comment by elijaharita** [comment]
Have you tried the solution I posted above? It works for me every time, but I haven't received any feedback from others.

**Comment by RaeesBhatti** [comment]
`ESRCH` error means that the process that was supposed to be stopped couldn't be found. Unfortunately, I don't have a Windows device at hand to debug this but making sure dependencies are installed would be a good start. If you're using `nuxt`, making sure that you have a `scripts` entry in your `package.json` for `dev` or `start` that maps to `nuxt` would be a good idea too. Like so:
```
...
    "scripts": {
        "dev": "nuxt",
    },
...
```

**Comment by RaeesBhatti** [comment]
Having `nuxt` as a dependency is also a requirement to detect Nuxt as framework.

In @zync09's  case It seems like `yarn` is being detected as the framework, which is odd because we don't have a detector profile that maps to `yarn`. It would be helpful if you can share your `package.json`, specifically the `dependencies` and `scripts` part.

**Comment by SammyIsra** [comment]
In my case, I am using Gatsby, not Nuxt. I did try the solution - in my `package.json` I have this script: `"dev": "gatsby develop"` but that doesn't fix the issue. It doesn't seem to change anything on my end. 

Is there anything I can do on my end to figure out what was the process that was expected to be closed?

**Comment by RaeesBhatti** [comment]
@SammyIsra Can you please post your `package.json` contents here! `dependencies`, `devDependencies` and `scripts` specifically.

Also, does `Gatsby develop` ever run when you run `netlify dev`, can you see the Gatsby related logs in the terminal?

**Comment by SammyIsra** [comment]
@RaeesBhatti For your second question, I don't see any output from `gatsby develop`. This is the entire output from running `netlify-dev`:
![image](https://user-images.githubusercontent.com/8962228/79059558-30f72880-7c30-11ea-941c-bbda1060ebac.png)

For the contents of my `package.json`, I should note that this is almost identical than the Gatsby starter found here: https://www.netlifycms.org/docs/start-with-a-template/

Here are the contents:
```
  "dependencies": {
    "@types/styled-components": "^5.0.1",
    "babel-plugin-styled-components": "^1.10.7",
    "bulma": "^0.8.0",
    "gatsby": "^2.13.31",
    "gatsby-image": "^2.0.23",
    "gatsby-plugin-netlify": "^2.0.6",
    "gatsby-plugin-netlify-cms": "^4.1.6",
    "gatsby-plugin-purgecss": "^4.0.0",
    "gatsby-plugin-react-helmet": "^3.0.4",
    "gatsby-plugin-sass": "^2.0.7",
    "gatsby-plugin-sharp": "^2.2.9",
    "gatsby-plugin-styled-components": "^3.2.1",
    "gatsby-plugin-typescript": "^2.3.1",
    "gatsby-remark-copy-linked-files": "^2.0.7",
    "gatsby-remark-images": "^3.1.6",
    "gatsby-remark-relative-images": "^0.3.0",
    "gatsby-source-filesystem": "^2.0.26",
    "gatsby-transformer-remark": "^2.6.9",
    "gatsby-transformer-sharp": "^2.1.9",
    "lodash": "^4.17.15",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms-app": "^2.9.6",
    "netlify-cms-media-library-cloudinary": "^1.3.2",
    "netlify-cms-media-library-uploadcare": "^0.5.2",
    "node-fetch": "^2.6.0",
    "node-sass": "^4.11.0",
    "prop-types": "^15.6.0",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "react-helmet": "^5.2.0",
    "styled-components": "^5.1.0",
    "uuid": "^3.2.1"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "main": "n/a",
  "scripts": {
    "clean": "gatsby clean",
    "start": "npm run develop",
    "build": "npm run clean && gatsby build",
    "develop": "npm run clean && gatsby develop",
    "format": "prettier --trailing-comma es5 --no-semi --single-quote --write \"{gatsby-*.js,src/**/*.js}\"",
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "npm run develop"
  },
  "devDependencies": {
    "prettier": "^1.15.3"
  }
```

Hope that helps! 🙏

**Comment by RaeesBhatti** [comment]
Thank you all for your patience. It sure took a while but I was able to hunt down the bug. It seems like Windows doesn't allow invoking binaries without full path.
We have a fix in PR, it will be released soon. In the mean time, you can checkout the branch to test it locally. https://github.com/netlify/cli/pull/816

**Comment by RaeesBhatti** [comment]
Please note that Netlify Dev is beta software. I know that it is very frustrating when your tools don't work but we have very limited resources for this project. We're hoping that all of us as a community can improve and support it.

**Comment by SammyIsra** [comment]
That's great to hear, thank you so much! 

I have a follow up question. If this happened on all Windows machines, how come the solution mentioned above worked when using Nuxt?

**Comment by RaeesBhatti** [comment]
It might be that the solution worked in WSL platform and not on Windows. I'm not sure exactly.

**Comment by SammyIsra** [comment]
Understood. Is there a way for me to tell which version of the CLI will contain this change?

**Comment by RaeesBhatti** [comment]
`netlify-cli@2.44.0` has just been released that contains this fix.

**Comment by zync09** [comment]
Thank you for this @RaeesBhatti ! Can confirm this is now working with my NUXT project.
